### ISSUE TITLE
Verbose Text overhang still on this latest release (494733f)

### ISSUE THREAD

**Issue by esafeddie** [dortania/build-repo#19]
I just updated OC to the latest version and that text Bug is still there on the Boot Menu.
Had to revert to one I built from XCODE5 Artifact that corrected the glitch (see attached)
![16165718](https://user-images.githubusercontent.com/7919587/219443575-ad551358-2402-419b-b474-51547768d9b8.png)
![16170407](https://user-images.githubusercontent.com/7919587/219443623-99ccb85c-a70e-40a9-9bff-20318e6672b8.png)

**Comment by perez987** [comment]
Good afternoon @esafeddie there is a pull request in progress
https://github.com/acidanthera/OpenCorePkg/pull/426

OpenCore bugtracker is this
https://github.com/acidanthera/bugtracker/issues
now we are in the build-repo bugtracker.

**Comment by averycblack** [comment]
Please use the [Acidanthera bug tracker](https://github.com/acidanthera/bugtracker/issues)
